ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'REQUEST_RECEIVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'REQUEST_ACCEPTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'REQUEST_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'REQUEST_ACTIVE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'REQUEST_COMPLETED';
